### PR TITLE
Cargo fmt & clippy

### PR DESCRIPTION
**Pull request by max-sixty**
Cleaned a couple of things up as I was going through

Could add a test on these too

### CODE REVIEW

**Comment by max-sixty** [comment]
There are few remaining clippy lints, though I'm not sure where they're coming from - a file inside `target/`?

```
warning: redundant closure found
   --> /Users/maximilian/workspace/ballista/target/debug/build/ballista-754aa91e6c151734/out/ballista.rs:303:39
    |
303 |             let request = request.map(|b| grpc::BoxBody::map_from(b));
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove closure as shown: `grpc::BoxBody::map_from`
    |
    = note: #[warn(clippy::redundant_closure)] on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

warning: passing a unit value to a function
   --> /Users/maximilian/workspace/ballista/target/debug/build/ballista-754aa91e6c151734/out/ballista.rs:344:77
    |
344 |                             ResponseBody { kind: __Generated__Unimplemented(body) }
    |                                                                             ^^^^
    |
    = note: #[warn(clippy::unit_arg)] on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unit_arg
help: if you intended to pass a unit value, use a unit literal instead
    |
344 |                             ResponseBody { kind: __Generated__Unimplemented(()) }
    |                                                                             ^^

warning: very complex type used. Consider factoring parts into `type` definitions
   --> /Users/maximilian/workspace/ballista/target/debug/build/ballista-754aa91e6c151734/out/ballista.rs:355:30
    |
355 |               pub(super) kind: Kind<
    |  ______________________________^
356 | |                 // execute
357 | |                 grpc::Encode<grpc::unary::Once<<methods::Execute<T> as grpc::UnaryService<ExecuteRequest>>::Response>>,
358 | |                 // A generated catch-all for unimplemented service calls
359 | |                 (),
360 | |             >,
    | |_____________^
    |
    = note: #[warn(clippy::type_complexity)] on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#type_complexity
```

**Comment by andygrove** [comment]
@max-sixty This is coming from generated source create created by `build.rs`. Are you planning the travis cargo fmt check as well as part of this PR?

**Comment by andygrove** [comment]
See https://github.com/andygrove/ballista/issues/25 for more info

**Comment by max-sixty** [comment]
OK works!

**Pull request merged**
