### PR TITLE
Use a StatefulSet for executor and Kubernetes API instead of kubectl

### PR DESCRIPTION
**Pull request by sd2k**
This commit changes a few things about how we interact with Kubernetes. Specifically:

- following some advice in #35 the executor cluster is now created as a StatefulSet with an associated headless service.
- allow existing persistent volumes to be mounted into executor pods using the `--volumes` flag of `ballista create-cluster`. This still needs work - the access mode and capacity of the PVC are hardcoded right now.
- remove dependency on kubectl (#14) and use k8s_openapi and reqwest to create/delete clusters and applications. This means we can remove the dependency on gtmpl.
- use standard methods to decide how to communicate with Kubernetes (#28): the ~/.kube/config file while outside Kubernetes, or the 'in-cluster config' (using environment variables) while inside Kubernetes - e.g. for the application pods). ~This does mean adding a git dependency for the currently unpublished `kubernetes` crate, so we should ask to get that published to crates.io!~ no longer relevant - uses the `kube` crate

A few things I noticed while writing this:

- the dev cycle is quite slow while working on the example, due to the way the Dockerfiles are laid out: making any changes to the ballista package will require a full rebuild of the example Dockerfile. Perhaps there's a better way of organising that! I'll have a think.
- error handling is going to get tricky, since there are so many possible error messages from Kubernetes alone! It might be worth looking into [snafu][] or [failure][] (although I think failure is falling out of favour?)
- it would be nice to adopt [structopt][] to handle argument parsing since we could end up with quite a lot of options!

Happy to make drastic changes to this by the way - it was partly a way for me to get stuck in! Let me know if there are parts you don't like.

[snafu]: https://docs.rs/snafu/0.4.3/snafu/
[failure]: https://github.com/rust-lang-nursery/failure
[structopt]: https://github.com/TeXitoi/structopt

### CODE REVIEW

**Comment by andygrove** [comment]
This is looking great, thanks @sd2k !

The current example requires deploying a docker image into the cluster. I am working on the physical query plan so we can just send a plan to the cluster instead and this will speed up dev cycles.

**Comment by sd2k** [comment]
Ah nice, that will be great.

Is there anything you dislike about this PR? I think it may actually be ready to merge if not. I'll create new issues to discuss the other things I mentioned.

**Comment by rrichardson** [comment]
I just gave it a quick once over.  Looks good to me.  Nice work!

**Comment by andygrove** [comment]
Thanks @sd2k !

**Pull request merged**
